export interface FoundationServiceEntry {
  service: string;
  operation: string;
  protected: true;
  permission: string;
}

export const foundationServiceRegistry: FoundationServiceEntry[] = [
  { service: "P01", operation: "workflow.start", protected: true, permission: "p01.workflow.start" },
  { service: "P01", operation: "workflow.act", protected: true, permission: "p01.workflow.act" },
  { service: "PS01", operation: "employee.read", protected: true, permission: "ps01.employee.read" },
  { service: "PS01", operation: "employee.governed_change", protected: true, permission: "ps01.employee.governed_change" },
  { service: "PS02", operation: "change.submit", protected: true, permission: "ps02.change.submit" },
  { service: "PS02", operation: "change.commit", protected: true, permission: "ps02.change.commit" },
  { service: "PS03", operation: "leave.submit", protected: true, permission: "ps03.leave.submit" },
  { service: "PS03", operation: "leave.approve", protected: true, permission: "ps03.leave.approve" },
  { service: "PS03", operation: "attendance.capture", protected: true, permission: "ps03.attendance.capture" },
  { service: "PS04", operation: "relay.write", protected: true, permission: "ps04.relay.write" },
  { service: "PS04", operation: "relay.replay", protected: true, permission: "ps04.relay.replay" },
  { service: "PS05", operation: "transfer.initiate", protected: true, permission: "ps05.transfer.initiate" },
  { service: "PS05", operation: "transfer.join", protected: true, permission: "ps05.transfer.join" },
  { service: "PS05", operation: "transfer.representation", protected: true, permission: "ps05.transfer.representation.file" },
  { service: "PS05", operation: "transfer.cancel", protected: true, permission: "ps05.transfer.cancel" },
  { service: "PS06", operation: "seniority.write", protected: true, permission: "ps06.seniority.write" },
  { service: "PS06", operation: "dpc.hold", protected: true, permission: "ps06.dpc.hold" },
  { service: "PS06", operation: "promotion.effect", protected: true, permission: "ps06.promotion.order.effect" },
  { service: "PS06", operation: "establishment.write", protected: true, permission: "ps06.establishment.write" },
  { service: "PS06", operation: "qsl.rule.write", protected: true, permission: "ps06.qsl.rule.write" },
  { service: "PS06", operation: "qsl.compute", protected: true, permission: "ps06.qsl.compute" },
  { service: "PS07", operation: "training.nomination", protected: true, permission: "ps07.nomination.submit" },
  { service: "PS07", operation: "training.complete", protected: true, permission: "ps07.nomination.complete" },
  { service: "PS08", operation: "apar.open", protected: true, permission: "ps08.apar.form.open" },
  { service: "PS08", operation: "apar.post_sr", protected: true, permission: "ps08.apar.post_sr" },
  { service: "PS09", operation: "case.open", protected: true, permission: "ps09.case.open" },
  { service: "PS09", operation: "penalty.impose", protected: true, permission: "ps09.penalty.impose" },
  { service: "PS10", operation: "salary.write", protected: true, permission: "ps10.salary.write" },
  { service: "PS10", operation: "payroll.compute", protected: true, permission: "ps10.payroll.compute" },
  { service: "PS10", operation: "payroll.approve", protected: true, permission: "ps10.payroll.approve" },
  { service: "PS10", operation: "payroll.disburse", protected: true, permission: "ps10.payroll.disburse" },
  { service: "PS11", operation: "case.create", protected: true, permission: "ps11.case.create" },
  { service: "PS11", operation: "service.verify", protected: true, permission: "ps11.service.verify" },
  { service: "PS11", operation: "pension.compute", protected: true, permission: "ps11.pension.compute" },
  { service: "PS11", operation: "ppo.issue", protected: true, permission: "ps11.ppo.issue" },
  { service: "PS12", operation: "sr.ingest", protected: true, permission: "ps12.sr.ingest" },
  { service: "PS13", operation: "document.create", protected: true, permission: "ps13.document.create" },
  { service: "PS13", operation: "document.attach", protected: true, permission: "ps13.document.attach" },
  { service: "PS14", operation: "analytics.read", protected: true, permission: "ps14.analytics.read" },
  { service: "PS14", operation: "analytics.refresh", protected: true, permission: "ps14.analytics.refresh" },
  { service: "PS14", operation: "analytics.drill_through", protected: true, permission: "ps14.analytics.drill_through" },
  { service: "P06", operation: "migration.stage", protected: true, permission: "p06.migration.stage" },
];
