import { canonicalApiErrorCodes } from "../http/errors";

export const openApiContractFiles = [
  "docs/contracts/openapi/P01-workflow.yaml",
  "docs/contracts/openapi/PS01.yaml",
  "docs/contracts/openapi/PS02.yaml",
  "docs/contracts/openapi/PS03.yaml",
  "docs/contracts/openapi/PS04.yaml",
  "docs/contracts/openapi/PS05.yaml",
  "docs/contracts/openapi/PS06.yaml",
  "docs/contracts/openapi/PS07.yaml",
  "docs/contracts/openapi/PS08.yaml",
  "docs/contracts/openapi/PS09.yaml",
  "docs/contracts/openapi/PS10.yaml",
  "docs/contracts/openapi/PS11.yaml",
  "docs/contracts/openapi/PS12.yaml",
  "docs/contracts/openapi/PS13.yaml",
  "docs/contracts/openapi/PS14.yaml",
  "docs/contracts/error-taxonomy.yaml",
] as const;

export const minimumRouteSet = [
  "POST /api/v1/workflow/instances",
  "POST /api/v1/workflow/instances/{instance_id}/advance",
  "POST /api/v1/workflow/instances/{instance_id}/approve",
  "POST /api/v1/workflow/instances/{instance_id}/reject",
  "POST /api/v1/workflow/instances/{instance_id}/send-back",
  "POST /api/v1/workflow/instances/{instance_id}/delegate",
  "POST /api/v1/workflow/instances/{instance_id}/cancel",
  "POST /api/v1/workflow/instances/{instance_id}/query",
  "GET /api/v1/workflow/instances/{instance_id}",
  "GET /api/v1/workflow/tasks",
  "GET /api/v1/employees",
  "POST /api/v1/employees",
  "GET /api/v1/employees/{id}",
  "GET /api/v1/employees/{id}/profile-360",
  "GET /api/v1/employees/changes",
  "GET /api/v1/employees/{id}/governed-changes",
  "POST /api/v1/employees/{id}/governed-changes",
  "POST /api/v1/governed-changes/{id}:approve",
  "POST /api/v1/governed-changes/{id}:reject",
  "POST /api/v1/personal-details/change-requests",
  "GET /api/v1/personal-details/change-requests",
  "POST /api/v1/personal-details/change-requests/{id}:approve",
  "POST /api/v1/personal-details/change-requests/{id}:reject",
  "POST /api/v1/personal-details/change-requests/{id}:commit",
  "POST /api/v1/personal-details/change-requests/{id}:reverse",
  "POST /api/v1/atl/leave-applications",
  "GET /api/v1/atl/leave-applications",
  "POST /api/v1/atl/leave-applications/{id}/decision",
  "GET /api/v1/atl/leave-balances",
  "GET /api/v1/atl/leave-sr-outbox",
  "POST /api/v1/atl/attendance-captures",
  "POST /api/v1/atl/attendance-captures/{id}:regularise",
  "POST /api/v1/atl/overtime",
  "GET /api/v1/atl/payroll-signals",
  "GET /api/v1/leave-sr/outbox",
  "GET /api/v1/leave-sr/reconciliation",
  "POST /api/v1/leave-sr/outbox/{id}:relay",
  "POST /api/v1/leave-sr/outbox/{id}:replay",
  "POST /api/v1/leave-sr/outbox/{id}:discard",
  "POST /api/v1/transfers/orders",
  "GET /api/v1/transfers/orders",
  "POST /api/v1/transfers/orders/{id}/approve",
  "GET /api/v1/transfers/orders/{id}/clearance",
  "POST /api/v1/transfers/orders/{id}/clearances/{clearance_code}:complete",
  "POST /api/v1/transfers/orders/{id}/clearances/{clearance_code}:deem",
  "POST /api/v1/transfers/orders/{id}:relieve-and-join",
  "POST /api/v1/transfers/orders/{id}/representations",
  "GET /api/v1/transfers/representations",
  "POST /api/v1/transfers/representations/{id}:retain",
  "POST /api/v1/transfers/orders/{id}:cancel",
  "POST /api/v1/transfers/orders/{id}:deem-relieved",
  "POST /api/v1/promotions/seniority-lists",
  "POST /api/v1/promotions/seniority-lists/{id}:publish",
  "POST /api/v1/promotions/seniority-lists/{id}:finalise",
  "POST /api/v1/promotions/cases",
  "POST /api/v1/promotions/cases/{id}:hold-dpc",
  "POST /api/v1/promotions/cases/{id}:issue-orders",
  "POST /api/v1/promotions/orders/{id}:effect",
  "POST /api/v1/promotions/macp",
  "GET /api/v1/promotions/summary",
  "POST /api/v1/training/sessions",
  "POST /api/v1/training/nominations",
  "POST /api/v1/training/nominations/{id}:approve",
  "POST /api/v1/training/nominations/{id}:complete",
  "GET /api/v1/training/summary",
  "POST /api/v1/apar/forms",
  "POST /api/v1/apar/forms/{id}:submit-self",
  "POST /api/v1/apar/forms/{id}:report",
  "POST /api/v1/apar/forms/{id}:review",
  "POST /api/v1/apar/forms/{id}:accept",
  "POST /api/v1/apar/forms/{id}:post-sr",
  "POST /api/v1/apar/forms/{id}:release-sealed-cover",
  "GET /api/v1/apar/summary",
  "POST /api/v1/disciplinary/cases",
  "POST /api/v1/disciplinary/cases/{id}:charge",
  "POST /api/v1/disciplinary/cases/{id}:inquiry-report",
  "POST /api/v1/disciplinary/cases/{id}:penalty",
  "POST /api/v1/disciplinary/cases/{id}:appeal",
  "GET /api/v1/disciplinary/summary",
  "POST /api/v1/payroll/salary-structures",
  "POST /api/v1/payroll/adjustments",
  "POST /api/v1/payroll/runs",
  "POST /api/v1/payroll/runs/{id}:lock-inputs",
  "POST /api/v1/payroll/runs/{id}:compute",
  "POST /api/v1/payroll/runs/{id}:reconcile",
  "POST /api/v1/payroll/runs/{id}:approve",
  "POST /api/v1/payroll/runs/{id}:lock",
  "POST /api/v1/payroll/runs/{id}:disburse",
  "GET /api/v1/payroll/summary",
  "POST /api/v1/pension/cases",
  "POST /api/v1/pension/cases/{id}:verify-service",
  "POST /api/v1/pension/cases/{id}:compute",
  "POST /api/v1/pension/cases/{id}:sanction",
  "POST /api/v1/pension/cases/{id}:issue-ppo",
  "GET /api/v1/pension/summary",
  "POST /api/v1/sr/ingest",
  "POST /api/v1/sr/ingest/reversal",
  "GET /api/v1/sr/ingest/{ingestion_request_id}",
  "GET /api/v1/sr/employees/{id}/timeline",
  "GET /api/v1/sr/events/{id}",
  "POST /api/v1/sr/events/{id}/corrigendum",
  "POST /api/v1/sr/events/{id}/dispute",
  "POST /api/v1/sr/disputes/{id}/resolve",
  "POST /api/v1/documents",
  "GET /api/v1/documents",
  "GET /api/v1/documents/{id}",
  "POST /api/v1/documents:attach",
  "GET /api/v1/documents/{id}/versions",
  "POST /api/v1/documents/{id}:checkin",
  "POST /api/v1/documents/{id}:supersede",
  "POST /api/v1/legal-holds",
  "POST /api/v1/legal-holds/{id}:approve-placement",
  "POST /api/v1/legal-holds/{id}:release",
  "GET /api/v1/documents/{id}/retention",
  "POST /api/v1/documents/{id}:extend-retention",
  "POST /api/v1/analytics/marts:refresh",
  "GET /api/v1/analytics/dashboards/executive-readiness",
  "GET /api/v1/analytics/drill-through",
  "GET /api/v1/analytics/data-health",
  "GET /api/v1/analytics/summary",
] as const;

export const apiContractSnapshot = {
  basePath: "/api/v1",
  protected: true,
  authHook: "Authorization.check",
  correlationHeader: "X-Correlation-Id",
  idempotencyHeader: "Idempotency-Key",
  pagination: { limit: 25, maxLimit: 100, next_cursor: null },
  errorCodes: canonicalApiErrorCodes,
};
