#!/usr/bin/env bash
###############################################################################
# Pipeline driver — the EXTERNAL orchestrator generated by the plan-to-pipeline skill.
# Generic + self-locating: copy this file (unchanged) into your <pipeline>/ dir.
#
#   - Runs ONE phase per FRESH agent session (context never spans phases).
#   - Verifies each phase's exit_criteria OUTSIDE the model (independent oracle).
#   - gate:auto  -> advance automatically on GREEN.
#   - gate:human -> after GREEN, PARK until approvals/<id>.approved exists.
#   - Resumable (.state/<id>.status markers; done phases skipped, never re-run).
#   - Hard-stop on RED (no retry-loop -> no budget runaway).
#   - Safe by default: does NOTHING unless --execute AND you are on a non-main branch.
#
# Layout (all relative to THIS script's directory):
#   phases.yaml  prompts/  checks/  .state/  approvals/  logs/
# Paths inside phases.yaml (prompt, exit_criteria) are relative to the git repo root.
#
# Usage:
#   ./run.sh                 # dry-run: show state + preview the next phase's check
#   ./run.sh --status        # print every phase's state and exit
#   ./run.sh --execute       # run for real (requires a non-main branch)
#   ./run.sh --from <ID>     # resume/force-start at a phase
#   ./run.sh --reset <ID>    # clear a phase's state marker (files untouched)
#
# Env: CLAUDE_CMD (default: claude) · CLAUDE_FLAGS (default: --permission-mode acceptEdits) ·
#      CLAUDE_MODEL (optional) · NOTIFY_CMD (optional; called with a message on park/red)
###############################################################################
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git -C "$HERE" rev-parse --show-toplevel 2>/dev/null || echo "$HERE")"
MANIFEST="$HERE/phases.yaml"
STATE="$HERE/.state"; APPROVALS="$HERE/approvals"; LOGS="$HERE/logs"
mkdir -p "$STATE" "$APPROVALS" "$LOGS"
cd "$ROOT"

CLAUDE_CMD="${CLAUDE_CMD:-claude}"
CLAUDE_FLAGS="${CLAUDE_FLAGS:---permission-mode acceptEdits}"
[ -n "${CLAUDE_MODEL:-}" ] && CLAUDE_FLAGS="$CLAUDE_FLAGS --model $CLAUDE_MODEL"
TIMEOUT_BIN="$(command -v timeout || command -v gtimeout || true)"

EXECUTE=0; STATUS=0; FROM=""; RESET=""
while [ $# -gt 0 ]; do case "$1" in
  --execute) EXECUTE=1;;
  --status)  STATUS=1;;
  --from)    FROM="$2"; shift;;
  --reset)   RESET="$2"; shift;;
  -h|--help) sed -n '2,34p' "$0"; exit 0;;
  *) echo "unknown arg: $1"; exit 2;;
esac; shift; done

notify(){ echo ">> $*"; [ -n "${NOTIFY_CMD:-}" ] && "$NOTIFY_CMD" "$*" || true; }
state_of(){ cat "$STATE/$1.status" 2>/dev/null || echo pending; }
set_state(){ echo "$2" > "$STATE/$1.status"; }
approved(){ [ -f "$APPROVALS/$1.approved" ]; }

if [ -n "$RESET" ]; then rm -f "$STATE/$RESET.status"; echo "reset $RESET"; exit 0; fi

read_phases(){
python3 - "$MANIFEST" <<'PY'
import sys,yaml
m=yaml.safe_load(open(sys.argv[1]))
for p in m.get("phases",[]):
    print("\t".join([p["id"],p.get("name",""),p["prompt"],str(p.get("exit_criteria","true")),p.get("gate","human"),",".join(p.get("depends_on") or [])]))
PY
}
PHASE_TIMEOUT="$(python3 - "$MANIFEST" <<'PY'
import sys,yaml;print(yaml.safe_load(open(sys.argv[1])).get("defaults",{}).get("phase_timeout_seconds",3600))
PY
)"

if [ "$STATUS" = 1 ]; then
  echo "== pipeline state =="
  while IFS=$'\t' read -r id name prompt ex gate deps; do
    printf "  %-8s %-14s %s\n" "$id" "[$(state_of "$id")]" "$name"
  done < <(read_phases); exit 0
fi

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
if [ "$EXECUTE" = 1 ]; then
  if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "REFUSING to --execute on '$branch'. Create a sandbox branch first:  git checkout -b pipeline-run"; exit 3
  fi
  echo "== EXECUTE on branch '$branch' | agent: $CLAUDE_CMD $CLAUDE_FLAGS | timeout ${PHASE_TIMEOUT}s (${TIMEOUT_BIN:-none}) =="
else
  echo "== DRY-RUN (no changes). Pass --execute on a sandbox branch to run for real. Branch: '$branch' =="
fi

started=0
while IFS=$'\t' read -r id name prompt exit_cmd gate deps; do
  if [ -n "$FROM" ] && [ "$started" = 0 ]; then
    [ "$id" = "$FROM" ] && started=1 || { echo "  skip $id (before --from $FROM)"; continue; }
  fi
  st="$(state_of "$id")"
  [ "$st" = done ] && { echo "  ✓ $id done — skip"; continue; }

  if [ "$st" = awaiting-approval ]; then
    if approved "$id"; then set_state "$id" done; echo "  ✓ $id approved → done"; continue; fi
    notify "PARKED at human gate: $id ($name). Approve:  touch $APPROVALS/$id.approved  then re-run."; exit 0
  fi
  for d in $(echo "$deps" | tr ',' ' '); do
    [ -n "$d" ] && [ "$(state_of "$d")" != done ] && { echo "  ⏸ $id blocked on $d ($(state_of "$d"))"; exit 0; }
  done

  echo ""; echo "── $id : $name ──"; echo "   prompt: $prompt"; echo "   verify: $exit_cmd"; echo "   gate:   $gate"
  if [ "$EXECUTE" = 0 ]; then
    echo "   [dry-run] would run a fresh agent session on the prompt, then verify. Preview of exit_criteria:"
    ( eval "$exit_cmd" ) 2>&1 | sed 's/^/     /' || true
    echo "   → stop (dry-run shows the next actionable phase only)."; exit 0
  fi

  set_state "$id" running
  snap="$(git rev-parse --short HEAD 2>/dev/null || echo '?')"
  log="$LOGS/${id}-$(date +%Y%m%d-%H%M%S 2>/dev/null || echo run).log"
  echo "   git snapshot: $snap  (rollback: git reset --hard $snap)"; echo "   running fresh session → $log"
  if [ -n "$TIMEOUT_BIN" ]; then
    "$TIMEOUT_BIN" "$PHASE_TIMEOUT" $CLAUDE_CMD -p "$(cat "$prompt")" $CLAUDE_FLAGS 2>&1 | tee "$log"
  else
    echo "   (no timeout binary; running without wall-clock cap — install coreutils for gtimeout)"
    $CLAUDE_CMD -p "$(cat "$prompt")" $CLAUDE_FLAGS 2>&1 | tee "$log"
  fi

  echo "   verifying exit_criteria (external oracle)…"
  if eval "$exit_cmd"; then
    if [ "$gate" = auto ]; then set_state "$id" done; echo "   ✓ GREEN + gate:auto → advancing"; continue
    else set_state "$id" awaiting-approval
      notify "GREEN — $id ($name) passed checks; PARKED at human gate. Review then:  touch $APPROVALS/$id.approved  and re-run."; exit 0
    fi
  else
    set_state "$id" failed
    notify "RED — $id ($name) failed exit_criteria. HARD STOP (no retry). Log: $log. Fix then re-run (or --reset $id)."; exit 1
  fi
done < <(read_phases)

echo ""; echo "🎉 all phases done."
